[build]
  command = "NODE_ENV=development pnpm install && NODE_ENV=production pnpm --filter unjquery-web... run build"
  publish = "packages/unjquery-web/.next"

[context.production.environment]
  NPM_FLAGS = "--prefer-offline --no-audit --progress false"
  NODE_VERSION = "20"
  NODE_ENV = "production"
