[build]
  command = "pnpm install && pnpm --filter unjquery-web... run build"
  publish = "packages/unjquery-web/.next"

[context.production.environment]
  NPM_FLAGS = "--prefer-offline --no-audit --progress false"
  NODE_VERSION = "16"
  NODE_ENV = "production"
